### PR TITLE
Basic Forecast and Time Machine tests

### PR DESCRIPTION
**Pull request by anthonyfalzetti**
Add ExVcr so tests don’t make live api calls

### CODE REVIEW

**Comment by anthonyfalzetti** [comment]
I updated the test.exs to have a fake api key since CI doesn't set the the key in the ENV. If it would be more preferred I can set this back to look for the ENV (since that is what would happen in production anyways), if you can update CI to set this value.

**Review by techgaun — APPROVED** [review]
awesome, looks really good @anthonyfalzetti

**Comment by techgaun** [comment]
@anthonyfalzetti I've added the api key as an environment variable `DARKSKY_API_KEY`. If you can update that, I am happy to merge this right after

**Comment by anthonyfalzetti** [comment]
@techgaun removed the commit that updated the `test.exs`

**Comment by techgaun** [comment]
@anthonyfalzetti trying to figure out whats going on with build. I might just switch over to travis at some point. if the build continues to be stuck, I might just switch over sooner than later. thanks for your patience

**Comment by anthonyfalzetti** [comment]
yeah I was trying to figure out if there is a way for me to kill it, but so far I haven't figured it out

**Comment by techgaun** [comment]
@anthonyfalzetti I am going ahead and merge this. I pulled your stuff locally and works just fine.

**Comment by anthonyfalzetti** [comment]
TY

**Comment by anthonyfalzetti** [comment]
@techgaun  Apparently we need to add 
`mix local.rebar --force`
to the build step to get the tests to pass again in semaphoreci
source: https://semaphoreci.com/community/tutorials/setting-up-continuous-integration-for-an-elixir-project-using-semaphore

**Comment by techgaun** [comment]
@anthonyfalzetti I think that may not be necessary if there's no dependency that use rebar but I will give that a try. thanks!

**Comment by techgaun** [comment]
@anthonyfalzetti looks like it did the trick. thanks @anthonyfalzetti

**Comment by anthonyfalzetti** [comment]
yay back to green

**Pull request merged**
